export const ASSIGMENT_DETAILS_REQUEST = 'ASSIGMENT_DETAILS_REQUEST';
export const ASSIGMENT_DETAILS_SUCCESS = 'ASSIGMENT_DETAILS_SUCCESS';
export const ASSIGMENT_DETAILS_FAIL = 'ASSIGMENT_DETAILS_FAIL';
