export const CLASS_LIST_REQUEST = "CLASS_LIST_REQUEST";
export const CLASS_LIST_SUCCESS = "CLASS_LIST_SUCCESS";
export const CLASS_LIST_FAIL = "CLASS_LIST_FAIL";

export const CLASS_DETAILS_REQUEST = "CLASS_DETAILS_REQUEST";
export const CLASS_DETAILS_SUCCESS = "CLASS_DETAILS_SUCCESS";
export const CLASS_DETAILS_FAIL = "CLASS_DETAILS_FAIL";

export const CLASS_CREATE_REQUEST = "CLASS_CREATE_REQUEST";
export const CLASS_CREATE_SUCCESS = "CLASS_CREATE_SUCCESS";
export const CLASS_CREATE_FAIL = "CLASS_CREATE_FAIL";
export const CLASS_CREATE_RESET = "CLASS_CREATE_RESET";

export const CLASS_SHOW_REQUEST = "CLASS_SHOW_REQUEST";
export const CLASS_SHOW_SUCCESS = "CLASS_SHOW_SUCCESS";
export const CLASS_SHOW_FAIL = "CLASS_SHOW_FAIL";

export const CLASS_SIGNATURE_REQUEST = "CLASS_SIGNATURE_REQUEST";
export const CLASS_SIGNATURE_SUCCESS = "CLASS_SIGNATURE_SUCCESS";
export const CLASS_SIGNATURE_FAIL = "CLASS_SIGNATURE_FAIL";

export const CLASS_QR_REQUEST = "CLASS_QR_REQUEST";
export const CLASS_QR_SUCCESS = "CLASS_QR_SUCCESS";
export const CLASS_QR_FAIL = "CLASS_QR_FAIL";

export const CLASS_CANCEL_REQUEST = "CLASS_CANCEL_REQUEST";
export const CLASS_CANCEL_SUCCESS = "CLASS_CANCEL_SUCCESS";
export const CLASS_CANCEL_FAIL = "CLASS_CANCEL_FAIL";
export const CLASS_CANCEL_RESET = "CLASS_CANCEL_RESET";

export const CLASS_DAY_REQUEST = "CLASS_DAY_REQUEST";
export const CLASS_DAY_SUCCESS = "CLASS_DAY_SUCCESS";
export const CLASS_DAY_FAIL = "CLASS_DAY_FAIL";

export const CLASS_ALL_REQUEST = "CLASS_ALL_REQUEST";
export const CLASS_ALL_SUCCESS = "CLASS_ALL_SUCCESS";
export const CLASS_ALL_FAIL = "CLASS_ALL_FAIL";
