export const CLASS_LIST_REQUEST = 'CLASS_LIST_REQUEST';
export const CLASS_LIST_SUCCESS = 'CLASS_LIST_SUCCESS';
export const CLASS_LIST_FAIL = 'CLASS_LIST_FAIL';

export const CLASS_DETAILS_REQUEST = 'CLASS_DETAILS_REQUEST';
export const CLASS_DETAILS_SUCCESS = 'CLASS_DETAILS_SUCCESS';
export const CLASS_DETAILS_FAIL = 'CLASS_DETAILS_FAIL';

export const CLASS_CREATE_REQUEST = 'CLASS_CREATE_REQUEST';
export const CLASS_CREATE_SUCCESS = 'CLASS_CREATE_SUCCESS';
export const CLASS_CREATE_FAIL = 'CLASS_CREATE_FAIL';
export const CLASS_CREATE_RESET = 'CLASS_CREATE_RESET';
