export const DASHBOARD_RESUMEN_REQUEST = 'DASHBOARD_RESUMEN_REQUEST';
export const DASHBOARD_RESUMEN_SUCCESS = 'DASHBOARD_RESUMEN_SUCCESS';
export const DASHBOARD_RESUMEN_FAIL = 'DASHBOARD_RESUMEN_FAIL';
