export const DOCENTE_LOGIN_REQUEST = "DOCENTE_LOGIN_REQUEST";
export const DOCENTE_LOGIN_SUCCESS = "DOCENTE_LOGIN_SUCCESS";
export const DOCENTE_LOGIN_FAIL = "DOCENTE_LOGIN_FAIL";

export const DOCENTE_LOGOUT = "DOCENTE_LOGOUT";

export const DOCENTE_REGISTER_REQUEST = "DOCENTE_REGISTER_REQUEST";
export const DOCENTE_REGISTER_SUCCESS = "DOCENTE_REGISTER_SUCCESS";
export const DOCENTE_REGISTER_FAIL = "DOCENTE_REGISTER_FAIL";

export const DOCENTE_DETAILS_REQUEST = "DOCENTE_DETAILS_REQUEST";
export const DOCENTE_DETAILS_SUCCESS = "DOCENTE_DETAILS_SUCCESS";
export const DOCENTE_DETAILS_FAIL = "DOCENTE_DETAILS_FAIL";
export const DOCENTE_DETAILS_RESET = "DOCENTE_DETAILS_RESET";

export const DOCENTE_UPDATE_PROFILE_REQUEST = "DOCENTE_UPDATE_PROFILE_REQUEST";
export const DOCENTE_UPDATE_PROFILE_SUCCESS = "DOCENTE_UPDATE_PROFILE_SUCCESS";
export const DOCENTE_UPDATE_PROFILE_FAIL = "DOCENTE_UPDATE_PROFILE_FAIL";
export const DOCENTE_UPDATE_PROFILE_RESET = "DOCENTE_UPDATE_PROFILE_RESET";

export const DOCENTE_LIST_REQUEST = "DOCENTE_LIST_REQUEST";
export const DOCENTE_LIST_SUCCESS = "DOCENTE_LIST_SUCCESS";
export const DOCENTE_LIST_FAIL = "DOCENTE_LIST_FAIL";
export const DOCENTE_LIST_RESET = "DOCENTE_LIST_RESET";

export const DOCENTE_DELETE_REQUEST = "DOCENTE_DELETE_REQUEST";
export const DOCENTE_DELETE_SUCCESS = "DOCENTE_DELETE_SUCCESS";
export const DOCENTE_DELETE_FAIL = "DOCENTE_DELETE_FAIL";

export const DOCENTE_UPDATE_REQUEST = "DOCENTE_UPDATE_REQUEST";
export const DOCENTE_UPDATE_SUCCESS = "DOCENTE_UPDATE_SUCCESS";
export const DOCENTE_UPDATE_FAIL = "DOCENTE_UPDATE_FAIL";
export const DOCENTE_UPDATE_RESET = "DOCENTE_UPDATE_RESET";

export const DOCENTE_RECOVER_REQUEST = "DOCENTE_RECOVER_REQUEST";
export const DOCENTE_RECOVER_SUCCESS = "DOCENTE_RECOVER_SUCCESS";
export const DOCENTE_RECOVER_FAIL = "DOCENTE_RECOVER_FAIL";
