export const DOCENTE_LIST_REQUEST = 'DOCENTE_LIST_REQUEST';
export const DOCENTE_LIST_SUCCESS = 'DOCENTE_LIST_SUCCESS';
export const DOCENTE_LIST_FAIL = 'DOCENTE_LIST_FAIL';

export const DOCENTE_DETAILS_REQUEST = 'DOCENTE_DETAILS_REQUEST';
export const DOCENTE_DETAILS_SUCCESS = 'DOCENTE_DETAILS_SUCCESS';
export const DOCENTE_DETAILS_FAIL = 'DOCENTE_DETAILS_FAIL';

export const DOCENTE_CREATE_REQUEST = 'DOCENTE_CREATE_REQUEST';
export const DOCENTE_CREATE_SUCCESS = 'DOCENTE_CREATE_SUCCESS';
export const DOCENTE_CREATE_FAIL = 'DOCENTE_CREATE_FAIL';

export const DOCENTE_UPDATE_REQUEST = 'DOCENTE_UPDATE_REQUEST';
export const DOCENTE_UPDATE_SUCCESS = 'DOCENTE_UPDATE_SUCCESS';
export const DOCENTE_UPDATE_FAIL = 'DOCENTE_UPDATE_FAIL';

export const DOCENTE_DELETE_REQUEST = 'DOCENTE_DELETE_REQUEST';
export const DOCENTE_DELETE_SUCCESS = 'DOCENTE_DELETE_SUCCESS';
export const DOCENTE_DELETE_FAIL = 'DOCENTE_DELETE_FAIL';
