export const ESTUDIANTE_LOGIN_REQUEST = 'ESTUDIANTE_LOGIN_REQUEST';
export const ESTUDIANTE_LOGIN_SUCCESS = 'ESTUDIANTE_LOGIN_SUCCESS';
export const ESTUDIANTE_LOGIN_FAIL = 'ESTUDIANTE_LOGIN_FAIL';

export const ESTUDIANTE_LOGOUT = 'ESTUDIANTE_LOGOUT';

export const ESTUDIANTE_REGISTER_REQUEST = 'ESTUDIANTE_REGISTER_REQUEST';
export const ESTUDIANTE_REGISTER_SUCCESS = 'ESTUDIANTE_REGISTER_SUCCESS';
export const ESTUDIANTE_REGISTER_FAIL = 'ESTUDIANTE_REGISTER_FAIL';

export const ESTUDIANTE_DETAILS_REQUEST = 'ESTUDIANTE_DETAILS_REQUEST';
export const ESTUDIANTE_DETAILS_SUCCESS = 'ESTUDIANTE_DETAILS_SUCCESS';
export const ESTUDIANTE_DETAILS_FAIL = 'ESTUDIANTE_DETAILS_FAIL';
export const ESTUDIANTE_DETAILS_RESET = 'ESTUDIANTE_DETAILS_RESET';

export const ESTUDIANTE_UPDATE_PROFILE_REQUEST =
  'ESTUDIANTE_UPDATE_PROFILE_REQUEST';
export const ESTUDIANTE_UPDATE_PROFILE_SUCCESS =
  'ESTUDIANTE_UPDATE_PROFILE_SUCCESS';
export const ESTUDIANTE_UPDATE_PROFILE_FAIL = 'ESTUDIANTE_UPDATE_PROFILE_FAIL';
export const ESTUDIANTE_UPDATE_PROFILE_RESET =
  'ESTUDIANTE_UPDATE_PROFILE_RESET';

export const ESTUDIANTE_LIST_REQUEST = 'ESTUDIANTE_LIST_REQUEST';
export const ESTUDIANTE_LIST_SUCCESS = 'ESTUDIANTE_LIST_SUCCESS';
export const ESTUDIANTE_LIST_FAIL = 'ESTUDIANTE_LIST_FAIL';
export const ESTUDIANTE_LIST_RESET = 'ESTUDIANTE_LIST_RESET';

export const ESTUDIANTE_DELETE_REQUEST = 'ESTUDIANTE_DELETE_REQUEST';
export const ESTUDIANTE_DELETE_SUCCESS = 'ESTUDIANTE_DELETE_SUCCESS';
export const ESTUDIANTE_DELETE_FAIL = 'ESTUDIANTE_DELETE_FAIL';

export const ESTUDIANTE_UPDATE_REQUEST = 'ESTUDIANTE_UPDATE_REQUEST';
export const ESTUDIANTE_UPDATE_SUCCESS = 'ESTUDIANTE_UPDATE_SUCCESS';
export const ESTUDIANTE_UPDATE_FAIL = 'ESTUDIANTE_UPDATE_FAIL';
export const ESTUDIANTE_UPDATE_RESET = 'ESTUDIANTE_UPDATE_RESET';

export const ESTUDIANTE_RECOVER_REQUEST = 'ESTUDIANTE_RECOVER_REQUEST';
export const ESTUDIANTE_RECOVER_SUCCESS = 'ESTUDIANTE_RECOVER_SUCCESS';
export const ESTUDIANTE_RECOVER_FAIL = 'ESTUDIANTE_RECOVER_FAIL';
