export const QR_CREATE_REQUEST = 'QR_CREATE_REQUEST';
export const QR_CREATE_SUCCESS = 'QR_CREATE_SUCCESS';
export const QR_CREATE_FAIL = 'QR_CREATE_FAIL';
export const QR_CREATE_RESET = 'QR_CREATE_RESET';
