export const REPORT_CREATE_REQUEST = 'REPORT_CREATE_REQUEST';
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS';
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL';
export const REPORT_CREATE_RESET = 'REPORT_CREATE_RESET';
